name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag amittz98/webapp:${{ github.run_number }}-${GITHUB_SHA}
    - name: docker login
      run: docker login -u ${{ secrets.SECRET_USER }} -p ${{ secrets.SECRET_PASS }}
    - name: docker push
      run: docker push amittz98/webapp:${{ github.run_number }}-${GITHUB_SHA}
